import "./css/style.css";
import "./vendor/bootstrap/css/bootstrap-grid.css";
import "./vendor/bootstrap/css/bootstrap-grid.min.css";
import "./vendor/bootstrap/css/bootstrap.css";
import "./vendor/bootstrap-icons/bootstrap-icons.css";
import "./vendor/bootstrap-icons/bootstrap-icons.min.css";
import "./vendor/bootstrap/css/bootstrap-utilities.css";
import "./vendor/boxicons/css/transformations.css";
import "./vendor/boxicons/css/boxicons.css";
import "./vendor/boxicons/css/boxicons.min.css";
import "./vendor/simple-datatables/style.css";

// import "./vendor/bootstrap/css/bootstrap-grid.rtl.css";
// import "./vendor/bootstrap/css/bootstrap.rtl.min.css";
// import "./vendor/bootstrap/css/bootstrap.rtl.css";

import "./vendor/remixicon/remixicon.css";
import "./vendor/boxicons/css/animations.css";

import Header from "./component/Header";
import Aside from "./component/Aside";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";
import Footer from "./component/Footer";
import Network from "./component/network";
// import Footer from "./component/Footer";
// import Main from "./component/Main";
// import Sidebar from "./component/Sidebar";

export const metadata = {
  title: 'dashborad',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

    <div>
    <Network/>
      {/* <!-- Favicons --> */}
      <link href="assets/img/favicon.png" rel="icon" />
      <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon" />

      {/* <!-- Google Fonts --> */}
      <link href="https://fonts.gstatic.com" rel="preconnect" />
      <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet" />

      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      <Header />
      <Aside />
      {/* <Sidebar/> */}
      {/* <Footer/> */}
      <ToastContainer
        position='top-right'
        autoClose={5000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme='light'
      />
      {/* <Footer/> */}
      {children}
    </div>
  )
}
