import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";
// import Network from "./component/network";
import "../dashboard/assets/css/orange-color.css";
import '../dashboard/assets/css/style.css';
import "../dashboard/assets/vendor/css/bootstrap.min.css";
import "../dashboard/assets/vendor/css/all.min.css";
import "../dashboard/assets/vendor/css/OverlayScrollbars.min.css";

export const metadata = {
    title: 'dashborad',
    description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
    return (
        <div>
            {/* <Network /> */}
            {/* <!-- Favicons --> */}
            <link rel="shortcut icon" href="favicon.png" />
            <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon" />


            <link href="https://fonts.gstatic.com" rel="preconnect" />
            <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet" />

            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
            <ToastContainer
                position='top-right'
                autoClose={5000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme='light'
            />

            {children}
        </div>
    )
}
